### ISSUE TITLE
Information from mainWindow.DisplayStats is unreadable on screen

### ISSUE THREAD

**Issue by kjpou1** [mono/CocosSharp#103]
My game has some large(ish) world co-ordinates which means that when I turn on the debug information that gets drawn to the bottom left of the screen the text is so small that you cannot read it (as the characters are about 3px high), the code is the standard:

``mainWindow.DisplayStats = true;

Is there any way to access this diagnostic information directly so that I can log it myself (either to application console, log file or on screen myself)?

Thanks, Adrian

**Comment by vancura** [comment]
https://github.com/mono/CocosSharp/pull/109 allows to change scaling of CCStats.

**Comment by kjpou1** [comment]
Closed via https://github.com/mono/CocosSharp/pull/109
