### ISSUE TITLE
Mac: When the app is in background, events are stopped, but Draw() not

### ISSUE THREAD

**Issue by vancura** [mono/CocosSharp#105]
Mac: When the app is in background, events are stopped, but Draw() calls not. Is that correct? [It just looks odd](http://vncr.in/ZNQ7) -- see when the window is blurred or focused by watching the titlebar.

**Comment by kjpou1** [comment]
@vancura do not use Draw method override to update your graphical elements.  Instead add a Schedule(); call in your constructor or AddedToScene override and use the Update method by overriding it.  Try to keep the Draw() method as clean as possible.

**Comment by vancura** [comment]
Thanks @kjpou1 for the explanation, makes sense.
