### ISSUE TITLE
CCDrawNode content size is always 0 x 0

### ISSUE THREAD

**Issue by rtabbara** [mono/CocosSharp#11]
When a user calls DrawRect, DrawCircle etc, the underlying triangle or line vertices are updated so that the primitives will render, but the ContentSize is not updated.

This will cause issues when adding children to a CCDrawNode, because if the content size is 0, then the local transform will be incorrect.

**Comment by kjpou1** [comment]
Closed via https://github.com/mono/CocosSharp/commit/a6915c05705b77fd92a489027a5c6bdd44c19ab4
