### ISSUE TITLE
Way to draw textured triangles.

### ISSUE THREAD

**Issue by kjpou1** [mono/CocosSharp#113]
Based off the discussion here http://forums.xamarin.com/discussion/31492/drawing-textured-triangles

1. Interface created to allow drawing textured triangles
2. Open CCDrawManger to be public so developers have access to lower functions

**Comment by vancura** [comment]
That would be awesome. I wrote a small kaleidoscope mesh renderer back in Unity, and it would be great to be able to port it to CocosSharp.

**Comment by kjpou1** [comment]
Some info:  http://http.developer.nvidia.com/GPUGems2/gpugems2_chapter03.html

**Comment by kjpou1** [comment]
See DrawPrimitives unit tests 
[GeometryBatchTest1](https://github.com/mono/CocosSharp/blob/master/tests/tests/classes/tests/DrawPrimitivesTest/DrawPrimitivesTest.cs#L241)
and
[GeometryBatchTest2](https://github.com/mono/CocosSharp/blob/master/tests/tests/classes/tests/DrawPrimitivesTest/DrawPrimitivesTest.cs#L331)

There is also a samples test [here] (https://github.com/mono/cocos-sharp-samples/tree/master/Spine)

**Comment by kjpou1** [comment]
@vancura see above

**Comment by vancura** [comment]
Cool! Thanks!
