### ISSUE TITLE
Mac NuGet package targets wrong platform

### ISSUE THREAD

**Issue by kjpou1** [mono/CocosSharp#115]
Reported by spotcatbug
See Forum post http://forums.xamarin.com/discussion/31650/cocossharp-1-3-1-on-mac-os-no-go

During the update of the iOS unified release for 1.3.1.0 the target platform for the Mac NuGet was modified to be platform lib/Xamarin.iOS10.  This needs to stay at lib/net40.

**Comment by rtabbara** [comment]
Successfully added MacOS.1.3.1.2 and MacOS.PCL.1.3.1.1 to Classic Mac projects.
