### ISSUE TITLE
WP8: CCSprite with PNG stream exception

### ISSUE THREAD

**Issue by jamesmontemagno** [mono/CocosSharp#118]
When using a .png image file with CCSprite on Windows Phone 8 it simply throws a stream exception. Converting to an xnb file fixes this. However, it works fine on iOS/Android and MonoGame says it should work.

**Comment by rtabbara** [comment]
Hi James,

I think you have to be careful with the format of native png files when
targeting WP8. Check out https://monogame.codeplex.com/discussions/360681
for more details.

**Comment by kjpou1** [comment]
This needs to be verified on Windows Phone 8.1 and if still happening open a new issue for Windows Phone 8.1
