### ISSUE TITLE
Load *.csb

### ISSUE THREAD

**Issue by xiaoliangde** [mono/CocosSharp#120]
How to load the csb type file？

suggest:
studio content type maybe same with xna content type

**Comment by kjpou1** [comment]
xaialoiangde 

There is support for the old .csb file format but we do not support the new format.  You can find examples here: https://github.com/mono/CocosSharp/tree/master/tests/tests/classes/tests/ExtensionsTest

You can find the old support in the [Extensions directory](https://github.com/mono/CocosSharp/tree/master/Extensions/CCBReader).

We have been looking into a few solutions including looking at support for [Sprite Builder](http://www.spritebuilder.com/) but that will be a future supported item.

**Comment by kjpou1** [comment]
closing this for now as answered.  Please reopen if there are anymore questions.
