### ISSUE TITLE
Content加载

### ISSUE THREAD

**Issue by xiaoliangde** [mono/CocosSharp#121]
自定义加载接口比较难完成。
如原生微软解决加密打包只需重写Content过程即可完成，正如前面issue也提到，整个资源能否统一一下（有编译的又有非编译的，或者直接简单的做法就是全部都编译，对于各种xml文件原本也是支持的），这样对于加载比较方便。
关于csb文件，如能提供一个工具直接转换为cs文件也不错（bin弄成xml未必好，反正都是栈结构不如直接上cs文件，对于框架写作或管理远远好于xml）。
强烈期待以上关于资源问题的解决。

**Comment by kjpou1** [comment]
xiaoliangde

I really apologize but is there anyway to explain in English?  Even Spanish, French, Portuguese, German or Italian would do.  I ran this through google translate but really do not get what you are asking here.

Anybody out there able to translate?

**Comment by kjpou1** [comment]
I am closing this for now.  You can reopen it if need be.

**Comment by xiaoliangde** [comment]
I sorry to hear that.
it is difficult to complete custom loading interface.
Such as original Microsoft solution to encryption package only need to override the Content process can be completed, as previously issue also mentioned that the whole resource can be unified(a compilation and non compilation, or directly to the simple approach is all the compilation, for various XML file was also support), so more convenient for loading.
On the CSB file, such as to provide a tool for direct conversion of CS file is also good (bin into XML is not necessarily good, anyway is stack structure as directly on the CS file, for writing or management framework is far better than XML).
Strong expectations about the resources to solve the problem above.
I will not use Chinese on GitHub.
Thanks for your reply.
I used xna to finish the game by Adobe Flash a fow years ago.

Flash can export a package that it can be directed to use by FlashBuilder.
So hope you can provide a tool to translate the .csb file.
And used the ProjectMercury(It can be found on http://codeplex.com/) solve the Particle Problem,It export the xml can be compile by Content Class.
So hope the resource can be unified.

**Comment by xiaoliangde** [comment]
it is first time I received non Chinese reply.
Thanks for your help.
I will do my best to write in english.
I look over the code that is difficult to unified loading resources​.
Also hope all the resource can be unified （by using or not using   ContentCompiler ）.Otherwise a bit messy.
Thanks for your help agin.
