### ISSUE TITLE
CCRepeat won't end

### ISSUE THREAD

**Issue by Krumelur** [mono/CocosSharp#130]
I'm trying to rotate a sprite 3 times. One full rotation takes 0.2 seconds. The code below will never reach the CCCallFunc().

```
this.RunActions (new CCRepeat (new CCRotateBy (0.2f, 360), 3), new CCCallFunc( () => {
				// When done, reset anchor and animation frame.
				this.AnchorPoint = currentAnchorPoint;
				this.SpriteFrame = this.defaultFrame;
			}));
```

**Comment by kjpou1** [comment]
Closed via commit https://github.com/mono/CocosSharp/commit/2fd9526a5797abc527dcfffaaacc67a040fae047
