### ISSUE TITLE
Feature request: add async/await support for actions

### ISSUE THREAD

**Issue by Krumelur** [mono/CocosSharp#135]
Creating CCSequences, CCSpawns and all that certainly works but if CocosSharp supported async/await with actions, chaining complex CCActions would become much clearer. I wrote an extension that simply uses a TaskCompletionSource to make RunAction() async.

https://gist.github.com/Krumelur/8fc95affb285bda9f8b8

This for instance also allows the usage of Task.WhenAny() to start a new action if one of the currently running actions has finished.

**Comment by kjpou1** [comment]
Closed by https://github.com/mono/CocosSharp/commit/6f0fe3fd3f66ab7eb2a6cb03f5ce91bafe05159b verified to work by @Krumelur
