### ISSUE TITLE
Difference between BoundingBoxTransformedToWorldspace and BoundingBox

### ISSUE THREAD

**Issue by kjpou1** [mono/CocosSharp#139]
Per forum discussion http://forums.xamarin.com/discussion/32475/iphone6-release-mode-messed-up

There is a difference between BoundingBoxTransformedToWorldspace and BoundingBox when used in Release mode on Device with arm64.

**Comment by smitcham** [comment]
In release mode the Height and Width of the CCRect returned by the call is correct, but the MinX and MinY values getting returned are twice their values when run in Debug.

**Comment by kjpou1** [comment]
This has been confirmed as fixed per Steven on the forum thread.

**Comment by smitcham** [comment]
Yes, I was able to remove all workarounds from my code.
