### ISSUE TITLE
TileMap cutting off large maps

### ISSUE THREAD

**Issue by kjpou1** [mono/CocosSharp#147]
As per forum discussion http://forums.xamarin.com/discussion/33946/cctiledmap-cutting-off-large-maps.

I'm having a problem with CCTileMap only rendering the first part of a large map. If I make the map smaller, the entire map renders. But once it gets past a certain size, the tiles stop rendering. A certain number of tiles will render starting from the upper left, but beyond a certain point no tiles are displayed.

**Comment by rtabbara** [comment]
Have opened up #148 to redefine issue.
