### ISSUE TITLE
iOS: System Japanese font character width/x-advance is too large

### ISSUE THREAD

**Issue by rtabbara** [mono/CocosSharp#149]
As per the forum discussion: http://forums.xamarin.com/discussion/33956/japanese-fonts.

**Comment by kjpou1** [comment]
This should be fixed with the new Unified CCLabel.  See test Label test LabelSystemFontUnicodeJapanese here : https://github.com/mono/CocosSharp/blob/master/tests/tests/classes/tests/LabelTestNew/LabelSystemFontUnicodeJapanese.cs
