### ISSUE TITLE
CCTileMap incorrectly uses the first tileset for all layers

### ISSUE THREAD

**Issue by charliekilian** [mono/CocosSharp#152]
TMX maps can have multiple tilesets. There is a bug happening where if a map has more than one tileset, any layers using a tileset other than the first one are rendered with the first tileset's tiles.

**Comment by charliekilian** [comment]
I have a test case and a fix for this in my pull request.

**Comment by rtabbara** [comment]
Thanks! I'll take a look at it asap and hopefully we can merge soon.

**Comment by kjpou1** [comment]
@charliekilian This issue can be closed from what I can tell correct?

**Comment by rtabbara** [comment]
Yep. Damn, should have included in the 1.3.2 release notes. I'll update
that.

**Comment by charliekilian** [comment]
Yes, that is correct.

**Comment by rtabbara** [comment]
Closed after ce7b35de352024447c395f80c1b74bab2fe36f0e
