### ISSUE TITLE
Overhaul CCSimpleAudioEngine

### ISSUE THREAD

**Issue by rtabbara** [mono/CocosSharp#157]
* For iOS, we were originally relying on the underlying AV Foundation due to an MG iOS audio issue, however those problems should have been fix, allowing us to unify iOS/other platforms to exclusively  make use of MG SoundEffect/SoundEffectInstance
* Add the ability to play multiple sound effect/music files concurrently (i.e. create multiple SoundEffectInstances per SoundEffect resource)
* A user should be able to stop/pause/resume a single sound effect instance
* <code> CCAudioEngine </code> should also allow the ability to stop/pause/resume all effect instances that belong to a single resource

**Comment by Krumelur** [comment]
@rtabbara Looking at this enhancement: are you aware that StopEffect() does not work on Android?

**Comment by jamikado** [comment]
Not sure StopEffect() is working on iOS either with the latest 1.5.0.1 PCL. StopAllEffects() seems to work but not StopEffect()

**Comment by kjpou1** [comment]
Should be closed by https://github.com/mono/CocosSharp/commit/65c001d8cb33dc1186a8bc30d64b6cd23a673981
