### ISSUE TITLE
Setting PositionX of CCRenderTexture results in wobbling on iPhone devices

### ISSUE THREAD

**Issue by Krumelur** [mono/CocosSharp#164]
The behavior is with CocosSharp 1.3.2.0 on iOS but does **not** show up in the Simulator.
See sample video attached. This has been recorded from an iPhone 6 running iOS8.2.

Video: https://dl.dropboxusercontent.com/u/111612273/ScrollProblem/ScrollIssue.mov
Demo project: https://dl.dropboxusercontent.com/u/111612273/ScrollProblem/ScrollIssue.zip

The node is scrolled using this code:

```
this.Schedule (dt => {
					texMountains.PositionX -= dt * FOREGROUND_SPEED_PIXEL_PER_SECOND / MOUNTAIN_PARALLAX_FACTOR;
					if(texMountains.PositionX <= -this.ContentSize.Width)
					{
						texMountains.PositionX += this.ContentSize.Width;
					}
				});
```

The slower the scrolling, the more obvious the effect becomes. **Using a CCSprite instead of CCRenderTexture fixes the issue.**

**Comment by rtabbara** [comment]
After #196, this is now a non-issue as a <code>CCRenderTexture</code> can no longer be attached as a child node. Instead, a user fetches the corresponding <code>CCRenderTexture.Sprite</code>.
