### ISSUE TITLE
CCTileMap.TilePropertiesForGID should not throw a KeyNotFoundException when passing a GID - it should return null

### ISSUE THREAD

**Issue by vchelaru** [mono/CocosSharp#165]
Currently users must catch exceptions and throw them away:

                                                        Dictionary<string, string> properties = null;
 
                                                        try
                                                        {
                                                                properties = tileMap.TilePropertiesForGID (info.Gid);
                                                        }
                                                        catch
                                                        {
                                                                // do nothing
                                                        }
 
TilePropertiesForGID should return null if no properties exist for the GID.

**Comment by rtabbara** [comment]
This was fixed in 154fbde4fb2e7137f5986d44d9755b980395888b
