### ISSUE TITLE
CCLabel leaks memory

### ISSUE THREAD

**Issue by Krumelur** [mono/CocosSharp#166]
I noticed that my game would crash in scenes that use a lot of CCLabel instances and created a little demo. You can find it here: https://dl.dropboxusercontent.com/u/111612273/CCLabel%20issue%20demo.zip

The ZIP includes an iOS project and a recording that demonstrates the problem.

In short:

* Create a CCLabel with a Truetype Font
* Add it to the scene
* Remove it again
* Loop over

Depending on device, it'll crash after 6000 labels but potentially much earlier. I have seen cases where for each label 800k of RAM got allocated and will never be freed again.

I have not tried if the problem also exists for sprite fonts. Will do that later.

This was tested against the latest sources of CocosSharp

**Comment by kjpou1** [comment]
Rene Thanks for finding this.  Could you verify if the commit above fixes this issue.

**Comment by Krumelur** [comment]
Please see for a fix: https://gist.github.com/Krumelur/7b7de1141dd24c01db74

The bitmap graphics contexts was not closed. I started playing around with the CGImage/UIImage and that made me convert things over to `using()` statements but that was not the problem. But I kept the changes, maybe you want to pull them in. I tried to fork the repo and submit a PR but XS would keep on changing the formatting and that caused too many differences.

**Comment by kjpou1** [comment]
Yes I would. What did I miss?  I thought I wasdisposing and losing everything. Thanks René

**Comment by Krumelur** [comment]
A balanced call to UIGraphics.BeginImageContext () was missing, so I added UIGraphics.EndImageContext ();

**Comment by kjpou1** [comment]
Am closing this one as it seems to be fixed.  Re-open or create a new one if there are more reports.
