### ISSUE TITLE
CCLabel does not display alpha correctly on Android

### ISSUE THREAD

**Issue by Krumelur** [mono/CocosSharp#173]
Using a CCLabel on Android produces results like the one shown in the image. I get these white borders around labels based on TTF. I had the same with all of my graphics until I converted them to XNBs. Is there anything that can be done about this?
Maybe related: I tried to set `IsAntialised` to true but that results in a null ref exception on Android.

![bildschirmfoto_2015-04-11_um_16-1 23 32](https://cloud.githubusercontent.com/assets/574373/7105979/60044ca0-e132-11e4-9250-7c3f4c3fc179.png)

**Comment by mikebluestein** [comment]
It's probsbly because Android is loading with non-premultiplied alpha, whereas iOS automatically does this when building for device iirc. You can see this with some of the sprites in the gone bananas sample as well. Using xnb is your best bet.

**Comment by Krumelur** [comment]
I'm not using any textures. This happens when using a true type font.

**Comment by vchelaru** [comment]
@Krumelur I haven't looked at the source, but I'd guess that the true type font still is rasterized into a texture internally, and during that process the texture may not use pre-multiplied alpha, as Mike mentions above.

**Comment by Krumelur** [comment]
Verified.
