### ISSUE TITLE
CCSprite (and CCNode) Rotation opposite of mathematical rotation

### ISSUE THREAD

**Issue by vchelaru** [mono/CocosSharp#174]
Mathematically, an increase in rotation values result in a counter-clockwise movement. This can be verified by checking various values in System.Math.Sin() and System.Math.Cos().

CocosSharp CCSprite (and all CCNodes) rotate clockwise movement as their Rotation property is increased. This means any manual implementation of rotation logic, such as firing a bullet from the tip of a rotated ship in an Asteroids game, requires the user to invert rotation values for custom logic.

I realize that correcting this would be a breaking change, but it may be better than having the permanent confusion of inverted rotation

**Comment by kjpou1** [comment]
Hey Victor

About the only explanation I can give is that cocos2d-x rotation works the same.  About it being changed we will need to evaluate if it is something that should be changed or just documented.

**Comment by kjpou1** [comment]
Actually you can see a reference to this here http://www.raywenderlich.com/25791/rotating-turrets-how-to-make-a-simple-iphone-game-with-cocos2d-2-x-part-2

Also here:  http://cocos2d-x.org/programmersguide/3/

Rotation

Changes the sprite's rotation, by positive or negative degrees. A positive value rotates the sprite clockwise, while a negative value rotates the sprite counter-clockwise. The default value is 0.
