### ISSUE TITLE
CCPoint.RotateByAngle Rotates counterclockwise instead of clockwise (as indicated by comments)

### ISSUE THREAD

**Issue by vchelaru** [mono/CocosSharp#178]
I wrote the following code:

```
CCPoint point = new CCPoint (100, 0);
Console.WriteLine ("Un-rotated point: " + point);
// This should rotate 90 degrees *clockwise*
point = CCPoint.RotateByAngle (point, CCPoint.Zero, CCMathHelper.ToRadians (90));
// We expect this to print out 0, -100
Console.WriteLine ("Rotated point: " + point);
```
The code in CCGeometry states:

```
/** Rotates a point counter clockwise by the angle around a pivot
    @param v is the point to rotate
    @param pivot is the pivot, naturally
    @param angle is the angle of rotation cw in radians
    @returns the rotated point
    @since v0.99.1
*/

public static CCPoint RotateByAngle(CCPoint v, CCPoint pivot, float angle)
{
```

Assuming "cw" means clockwise, then this should rotate clockwise resulting in a point of X=0, Y=-100.

Actual output:
```
Un-rotated point: CCPoint : (x=100, y=0)
Rotated point: CCPoint : (x=-4.371139E-06, y=100)
```
Notice that Y is positive, indicating a counterclockwise rotation (X value on rotated point is effectively 0, just some floating point error there).

CCPoint seems to be using a "mathematical rotation", but CCNode's Rotation value is inverted (as indicated in this issue https://github.com/mono/CocosSharp/issues/174 ).

If the intent is to rotate clockwise like CCNode,

**Comment by kjpou1** [comment]
@vchelaru : It does look like there is an inconsistency in the description.

The summary description is Rotates a point counter clockwise by the angle around a pivot but the actual argument does say "cw".  I will make that change to read "ccw" to correspond with the summary.

That can also be seen in the post http://forums.xamarin.com/discussion/38215/creating-custom-actions-rotatearoundto-part-1 as you mentioned there.

**Comment by kjpou1** [comment]
Fixed comment and closed by referencing commit
