### ISSUE TITLE
XML files should be distributed with CocosSharp templates

### ISSUE THREAD

**Issue by vchelaru** [mono/CocosSharp#179]
The CocosSharp.dll does not have an accompanying .XML file for in-IDE documentation. If this were distributed then developers would be able to learn code faster by looking at the pop-ups that appear when typing methods, arguments, and classes.

I don't know if this is something that is a problem with NuGet or with the default templates.

The documentation seems to exist for much of CocosSharp code:

```
       /*
        ccpSegmentIntersect returns YES if Segment A-B intersects with segment C-D
        @since v1.0.0
        */

        public static bool SegmentIntersect(CCPoint A, CCPoint B, CCPoint C, CCPoint D)
```

**Comment by kjpou1** [comment]
Closed via commits https://github.com/mono/CocosSharp/commit/8b7b0c8010c2507fad87cc91e68429fb2d853d3d and https://github.com/mono/CocosSharp/commit/92189beedb5a25d4804144483c5ef2d482746208
