### ISSUE TITLE
CCSpriteFontCache InternalLoadFont wrong algorithm

### ISSUE THREAD

**Issue by KalitaAlexey** [mono/CocosSharp#183]
```
foreach (var searchPath in searchPaths)
{
    foreach (string resolutionOrder in searchResolutionsOrder)
    {
        fontPath = Path.Combine(Path.Combine(searchPath, resolutionOrder), FontKey(fontName, fontSize));

        try
        {
            //TODO: for platforms with access to the file system, first check for the existence of the file 
            return contentManager.Load<SpriteFont>(fontPath);
        }
        catch (ContentLoadException)
        {
            // try other path
        }
    }
}
```
My fonts folder is in Content folder.
And to load my font I must add empty string to SearchResolutionOrder
```
CCContentManager.SharedContentManager.SearchResolutionOrder.Add("");
```
Is it excepted behavior?
Or maybe algorithm must be changed.

*Also in this method there is 3 copy-pasted chunks of code*

**Comment by kjpou1** [comment]
Hello Kalita

Great find Kalita.  Would you be willing to create a Pull Request to fix this issue since you already have a working example?  

Thanks in advance Kalita.

**Comment by KalitaAlexey** [comment]
@kjpou1 I need some help with that. Same code is in CCContentManager.GetAssetStream. I don't know is this code is correct or maybe it should be changed. Also I don't know what is SearchResolutionOrder.

**Comment by kjpou1** [comment]
Hey @KalitaAlexey 

No problem.  I think what is missing is a call like CheckDefaultPath in CCContentManager.cs.  If the same type of check is done in CCSpriteFontCache then that will probably fix your issue.

**Comment by KalitaAlexey** [comment]
I will make a pull request. Instead of calling each time CheckDefaultPath, I will change SearchResolutionOrder and SearchPaths to contain at least empty string. It will be a little optimization issue and also it will prevent futher bugs.

**Comment by kjpou1** [comment]
Kalita

Thank you very much!!!!
