### ISSUE TITLE
Tield map assets located in sub folders cannot be load.

### ISSUE THREAD

**Issue by gdwneo** [mono/CocosSharp#185]
Need to replace
<code>
if (!CCFileUtils.GetDirectoryName(imagename, out directory))
</code>
to
<code>
if (CCFileUtils.GetDirectoryName(imagename, out directory))
</code>
in <b>src\tileMap_parallax_nodes\CCTileMapInfo.cs line 445</b>, or it will not return the correct asset path.

**Comment by kjpou1** [comment]
Hey @gdwneo 

Thank you for finding this problem.  If you already have this working in your code would it be possible to submit a PR for it.

**Comment by gdwneo** [comment]
Seems I don't have permission to submit the PR....

**Comment by kjpou1** [comment]
Fixed by @gdwneo with PR https://github.com/mono/CocosSharp/pull/189
