### ISSUE TITLE
Update Nuspec's to support Xamarin unified API

### ISSUE THREAD

**Issue by rtabbara** [mono/CocosSharp#19]
As described [here](http://developer.xamarin.com/guides/cross-platform/macios/unified/), the introduction of the Unified API results in a library split where monotouch.dll -> Xamarin.iOS.dll, XamMac.dll -> Xamarin.Mac.dll. 

Additionally, when targeting iOS, the NuGet platform identifier has changed from MonoTouch10 to Xamarin.iOS10.

The Nuspec's need to be updated to incorporate these changes, making sure to also keep support for the Classic API as well.

**Comment by kjpou1** [comment]
See issue https://github.com/mono/CocosSharp/issues/98
