### ISSUE TITLE
Can't animate CCLabel by Opacity

### ISSUE THREAD

**Issue by grishaandrianov** [mono/CocosSharp#192]
protected override void AddedToScene () {
				var testLabel = new CCLabel ("Hello World!", "somefont.ttf", 40, CCLabelFormat.SystemFont) {Color = CCColor3B.Black };
				testLabel.IsOpacityCascaded = true;
				testLabel.Opacity = 0;
				AddChild (testLabel);
				testLabel.RunAction (new CCFadeTo (1f, 120));
			}

If set label opacity to 0 then CCFadeTo action does not work.
Without setting Opacity CCFadeTo action works fine.
Also it is strange that I should set testLabel.IsOpacityCascaded = true for CCLabel to animate it by Opacity.

**Comment by grishaandrianov** [comment]
I works now, I didn't do anything

**Comment by rtabbara** [comment]
Glad that it's sorted.
