### ISSUE TITLE
[Bug] CCTileMapLayer: Wrong rendering of hex tileset

### ISSUE THREAD

**Issue by omd** [mono/CocosSharp#197]
The rendering of hex tilesets is currently broken. In odd columns, starting at the 3rd one, the tiles are rendered at an increasingly wrong y-position. It appears as if the matrix based coordinate calculation is currently initialized with a wrong transformation matrix. I'll prepare a PR to fix this.

![tileset-bug](https://cloud.githubusercontent.com/assets/3092534/7447163/e84b7e16-f1f0-11e4-8f48-e205480f6777.png)

**Comment by omd** [comment]
With the fix proposed in #198, the rendering now looks ok again:

![tileset-bug](https://cloud.githubusercontent.com/assets/3092534/7447249/e52ee5ee-f1f3-11e4-89cb-44ca910811b0.png)

**Comment by rtabbara** [comment]
Hi @omd 

Would it be possible to provide us with the tile-map/tile-set or maybe a simplified version to add to our test suite? Unfortunately, the current version of Tiled no longer supports hexagonal maps so we don't have many test cases to work with.

**Comment by omd** [comment]
Sure, no problem. Should I attach the tile-map/-set here or update the corresponding test case and send in another PR?

**Comment by omd** [comment]
NB: Hex support is back in Tiled v0.11.0, see http://www.mapeditor.org/download.html

**Comment by rtabbara** [comment]
Oh, thanks for letting us know!

Just re the test-case, preferably as a PR, but if it's easier for you then you can just send them as an attachment.

**Comment by rtabbara** [comment]
Merged PR to fix this in commit c414abde6195085e39f6bb50df856b4703d121d0
