### ISSUE TITLE
Resetting properties of a CCNode when accessing it in CCLabel

### ISSUE THREAD

**Issue by Heikofant** [mono/CocosSharp#201]
I am working with CCLabel
`this.Label = new CCLabel (str, "arial", 150, CCLabelFormat.SpriteFont);`

Everything works fine, but as soon as I access any CCNode of that label, so
`var letter = this.Label[0]`

the accessed letter then appears white and on some devices displaced.

I can reset the color afterwards manually.

Seems there is a reset problem when accessing the single CCNodes inside a CCLabel.

**Comment by kjpou1** [comment]
@Heikofant 

This is as designed.  If you want the color to be the same what you need to do is set the label's `Cascaded` properties `IsColorCascaded` and/or `IsOpacityCascaded`.

Once the sprite of the corresponding letter it is obtained it is then under the developers control to do with as the developer sees fit.

**Comment by Heikofant** [comment]
The main thing is not about the color, it is about the character displacement.
As soon as I accessed a single character of the label, that character gets displaced on many devices.
By displacing I mean a change in the actual size which I can't fix.

**Comment by kjpou1** [comment]
@Heikofant 

Can you create a new issue with that specific problem and attach a sample project because in my tests I am not seeing that.
