### ISSUE TITLE
CCLabel: wrong color after fade animation

### ISSUE THREAD

**Issue by grishaandrianov** [mono/CocosSharp#202]
Let's create two identical labels, and run CCFadeTo animation for one of them from 0 to 255

		protected override void AddedToScene ()
		{
			base.AddedToScene ();
			_bounds = VisibleBoundsWorldspace;
			var testLabel1 = new CCLabel ("Hello World!", "font.ttf", 40, CCLabelFormat.SystemFont) {
				Color = CCColor3B.Black,
				AnchorPoint =  CCPoint.AnchorMiddle,
				Position = new CCPoint(_bounds.MaxX/2, 50),
				IsOpacityCascaded = true
			};
			var testLabel2 = new CCLabel ("Hello World!", "font.ttf", 40, CCLabelFormat.SystemFont) {
				Color = CCColor3B.Black,
				AnchorPoint =  CCPoint.AnchorMiddle,
				Position = new CCPoint(_bounds.MaxX/2, 120),
				IsOpacityCascaded = true
			};
			AddChild (testLabel1);
			AddChild (testLabel2);
			testLabel2.Opacity = 0;
			testLabel2.RunAction (new CCFadeTo (1f, 255));
		}

When animations are completed the result is two labels with different colors (black and gray). It seems like a bug. Or maybe I'm wrong somewhere? (Android platform)

Let's now create two another identical labels and run animations for them:

			testLabel3.Opacity = 0;
			testLabel3.RunAction (new CCSequence(new CCDelayTime(3f), new CCFadeTo (1f, 255)));

			testLabel4.RunAction (new CCSequence(new CCDelayTime(3f),  new CCCallFunc(() => { testLabel4.Opacity = 0; }), new CCFadeTo (1f, 255)));

When animations are completed testLabel4 has the black color (as it should to be), but testLabel3 is transparent.

**Comment by kjpou1** [comment]
@grishaandrianov 

Good catch and thank you!!!  We are able to recreate this problem and are working on a fix.

**Comment by kjpou1** [comment]
This should be fixed by the previous two commits.
