### ISSUE TITLE
CCGeometryBatch: Attach to scene graph

### ISSUE THREAD

**Issue by rtabbara** [mono/CocosSharp#207]
Right now a geometry batch gives the user the ability to render primitive drawing data, but is not derived from <code>CCNode</code> and hence cannot be attached to the scene graph.

Instead, to actually render to a scene, we have a Begin/End mechanic wherein users specify their drawing data, and then users subsequently have to manually call batch.Draw within some parent node.

It would be much cleaner and more inline with the design of other nodes if <code>CCGeometryBatch</code> was simply a child of <code>CCNode</code> and behave in a similar fashion to <code>CCDrawNode</code> &mdash;  that is, that we attach the batch to a parent node, and any geometry data specified will automatically be rendered accordingly whenever we visit a scene.

In fact, such a setup would further provide a natural avenue to alter <code>CCDrawNode</code> to leverage functionality of <code>CCGeometryBatch</code> by making it its parent class.

**Comment by kjpou1** [comment]
This also includes renaming to CCGeometryNode.  https://github.com/mono/CocosSharp/commit/424bf888c78cf6068a3fc0d6398114ae416198a2
