### ISSUE TITLE
Xamarin Studio CocosSharp templates should link against the latest NuGet

### ISSUE THREAD

**Issue by vchelaru** [mono/CocosSharp#234]
The latest cross-platform project includes NuGet packages 1.3.1 instead of 1.4.0. This may confuse new users who are starting up a project (especially those not used to NuGet) who attempt to use the new CCLabel code introduced in 1.4.0.

**Comment by kjpou1** [comment]
@vchelaru 

I think that might also be what is happening [here as well](https://forums.xamarin.com/discussion/42937/async-await-crashes-ios).

XS should automatically prompt for an update so it did not make sense to publish them again.  It seems that may not be the case though.

Thanks for reporting it and we will get new ones out with the next release.

I will mark this as closed for now but it is not forgotten.

**Comment by rtabbara** [comment]
@kjpou1 @vchelaru After the next upcoming release, I'll also make sure to provide an updated XS proj. template addin that bundles the latest NuGet packages for offline usage.

**Comment by kjpou1** [comment]
Also hoping that we can get the build server to build and update these templates automatically.
