### ISSUE TITLE
CCDrawNode: Bounding Rectangle

### ISSUE THREAD

**Issue by kjpou1** [mono/CocosSharp#236]
When drawing a CCDrawNode to a render texture the offset is the bottom left corner of the screen.  If the render texture is not large enough it will result in the drawing being clipped.

Since we are already calculating the min and max for the content size by traversing all the vertices we will also be able to create a bounding rectangle as well.

Add a new Property to CCDrawNode for BoundingRect which will return the Origin and Size of the vertices that are to be drawn.

See [forum](http://forums.xamarin.com/discussion/42915/how-to-save-line-drawing-correctly-as-sprite#latest) for a user description.

**Comment by rtabbara** [comment]
Am just wondering whether it might be easier to instead make use of the new <code>Visit(ref CCAffineTransform parentWorldTransform)</code> that was introduced as part of the renderer changes?

This will concatenate the parentTransform supplied with the node's local transform when rendering. Normally, when traversing a scene, the implicit transform will be the node's true parent transform. But when using render textures, a user can essentially pass in whatever transform they like giving them a lot of flexibility.

**Comment by kjpou1** [comment]
Rami, that could be as well.  Still think this is a good feature enhancement since we are basically calculating it anyway.  I am creating a test for the ContentSize calculation issue.  Could you create a test case scenario for what you are describing here?  That way we will have some more code to show users for this next release.  Lots of major changes and would like to have a referral of code for them.

**Comment by kjpou1** [comment]
Closed by https://github.com/mono/CocosSharp/commit/e179bc330e4d8dd339861d9861a39884a5c95094
