### ISSUE TITLE
CocosSharp templates do not appear in Xamarin Studio on Windows

### ISSUE THREAD

**Issue by vchelaru** [mono/CocosSharp#238]
I've enabled CocosSharp through the add-in manager on both Mac and PC. The templates appear just fine (under the cross-platform > App category), but they do not appear on Xamarin Studio on Windows.

![image](https://cloud.githubusercontent.com/assets/729631/8040713/d5d4f212-0dcf-11e5-80d3-96e11b3b454f.png)

![image](https://cloud.githubusercontent.com/assets/729631/8040705/c2bc83ca-0dcf-11e5-8f3c-607e27101bc9.png)

Many game developers use the Xamarin "Indie" license so they are required to use Xamarin Studio.

**Comment by rtabbara** [comment]
@vchelaru Thanks for pointing this out. I've confirmed after 3871341, that templates will appear on XS for Windows. I've built the new add-in locally, but a new public add-in will be made available to coincide with our upcoming NuGet releases.
