### ISSUE TITLE
Typo in parameter name in CCLayer's Visit()

### ISSUE THREAD

**Issue by Krumelur** [mono/CocosSharp#239]
Minor but it generates a warning in XS about different parameter name when overriding:

`public override void Visit (ref CCAffineTransform parentWorldTrans**from**)`

**Comment by kjpou1** [comment]
@Krumelur 

Where is that typo?  In CCNode?

**Comment by kjpou1** [comment]
Closed via commit https://github.com/mono/CocosSharp/commit/e177d72f51d03dc44423cee66d2d245dddc8c844

**Comment by kjpou1** [comment]
Thanks Rene
