### ISSUE TITLE
CCLabelTtf are invisible after ressurect on Windows Phone

### ISSUE THREAD

**Issue by grishaandrianov** [mono/CocosSharp#244]
I have tested this only on simulator.
If to tombstone CocosSharp game (tap start (windows) button) and then again return to the game (ressurect) all CCLabelTtf label are invisible.

**Comment by kjpou1** [comment]
@grishaandrianov 

What version of Windows Phone?  Can you try the CCLabel instead of CCLabelTtf because it is now obsolete and will be removed in the next full release.

**Comment by grishaandrianov** [comment]
Windows Phone 8.1 emulator. I wish to use CCLabel instead of CCLabelTtf but it doesn't exist for Windows Phone.

**Comment by grishaandrianov** [comment]
CocosSharp.WindowsPhone8, Emulator Windows Phone 8.1
I use SystemFont for Android and iOS, I have tried to use CCLabel for Windows Phone: SystemFont does't work at all and SpriteFont have different alignment and positions, I can't use it crossplafrom.

**Comment by kjpou1** [comment]
use CCLabel with CCLabelFormat.SpriteFont.  You really should be using windows phone 8.1.  https://github.com/mono/CocosSharp/wiki/Labels

**Comment by kjpou1** [comment]
I have just created a new Portable project with Windows Phone 8.1 that uses the following:

           // create and initialize a Label
            label = new CCLabel("Hello CocosSharp", "fonts/MarkerFelt", 22, CCLabelFormat.SpriteFont);

I then hit the window key/home and then hit the back button.  The label stills shows.  If this is still a problem could you let us know how to recreate this.

**Comment by grishaandrianov** [comment]
Did you use emulator or a device?

**Comment by kjpou1** [comment]
Both.  Simulator and just loaded up on my Nokia\Lumina 520.

**Comment by kjpou1** [comment]
I am going to close this for now as not being producible.  Please reopen if need be.
