### ISSUE TITLE
CardinalSpline rendering has extra line

### ISSUE THREAD

**Issue by vchelaru** [mono/CocosSharp#246]
The following sample code (inside of an object that implements CCDrawNode:

```
var splinePoints = new List<CCPoint> ();
splinePoints.Add (new CCPoint (0, 0));
splinePoints.Add (new CCPoint (50, 70));
splinePoints.Add (new CCPoint (0, 140));
splinePoints.Add (new CCPoint (100, 210));
splinePoints.Add (new CCPoint (0, 280));
splinePoints.Add (new CCPoint (150, 350));

int numberOfSegments = 64;
float tension = .05f;
base.DrawCardinalSpline (splinePoints, tension, numberOfSegments);
```

This results in the following rendered spline:

![image](https://cloud.githubusercontent.com/assets/729631/8398409/80a5ef5e-1daa-11e5-8a9a-d02f7552113a.png)

Screenshot was taken using Genymotion emulator, Nexus 7.

This was performed on CocosSharp build 1.5.0.1

I did not test this on other platforms, just Android.

**Comment by kjpou1** [comment]
Weird, I can not recreate this in master source but it does show up when using the package.

**Comment by kjpou1** [comment]
This should not be happening in source base.  See DrawPrimitiveTest that was added in commit above.
