### ISSUE TITLE
CCDrawNode.DrawEllipse includes rendering artifact on Android

### ISSUE THREAD

**Issue by vchelaru** [mono/CocosSharp#247]
The following code was used:

```
base.DrawEllipse (
	rect: new CCRect (0, 0, 130, 90),
	lineWidth: 7,
	color: CCColor4B.Gray);
```

This results in the following on Gemymotion Nexus 7 Android 5.0.0:

![image](https://cloud.githubusercontent.com/assets/729631/8398652/bd6fe462-1db4-11e5-9ba6-3faae68fa988.png)

This was reproduced using CocosSharp 1.5.0.1. It has only been tested on Android.

**Comment by kjpou1** [comment]
Closed via commit https://github.com/mono/CocosSharp/commit/b70de7dc9654cb151ab8bfc7d0d6c65725c8e197
