### ISSUE TITLE
CCDrawNode.DrawSegment takes only CCColor4F, other draw calls can take CCColor4B

### ISSUE THREAD

**Issue by vchelaru** [mono/CocosSharp#248]
It seems like all other functions for drawing primitives take both CCColor4B and CCColor4F, but DrawSegment takes only CCColor4F - may want to add a CCColor4B for consistency.

Furthermore, CCColor4B has pre-defined colors like CCColor4B.White, but CCColor4F does not.

**Comment by kjpou1** [comment]
Absolutely right Victor.  This should be closed via commit https://github.com/mono/CocosSharp/commit/7e23d01621f7ea8c53ee89224df69fac7ec6964c
