### ISSUE TITLE
CCDrawNode.DrawString takes x, y parameters, all other CCDrawNode calls take CCPoint

### ISSUE THREAD

**Issue by vchelaru** [mono/CocosSharp#249]
Every DrawXXXX call in CCDrawNode takes a CCPoint, even ones with few parameters like DrawDot, while CCDrawString takes x and y parameters. It should take a CCPoint to be consistent with all other calls.

**Comment by kjpou1** [comment]
This was more of a convenience method for CCDrawNode and was actually added for box2d debugging.  It also uses internally a MG SpriteBatch which will no longer work with the new Renderer Pipeline.  These will be removed and user will need to use CCLabel for their debugging text.

Will give this a while for anyone to comment on before removing and closing this.

**Comment by kjpou1** [comment]
These are now marked obsolete as they will no longer work with the Renderer Pipeline.  These should be replaced to use CCLabel.
