### ISSUE TITLE
CCDrawNode.DrawString does not seem to render anything

### ISSUE THREAD

**Issue by vchelaru** [mono/CocosSharp#250]
I don't know if there's some kind of setup necessary, but the following code does not result in any on-screen rendering:

```
base.DrawString (
	100, 
	100, 
	"test");
```

All other draw calls seem to work fine.

**Comment by kjpou1** [comment]
This was more of a convenience method for CCDrawNode and was actually added for box2d debugging.  It also uses internally a MG SpriteBatch which will no longer work with the new Renderer Pipeline.  These will be removed and user will need to use CCLabel for their debugging text.

Will give this a while for anyone to comment on before removing and closing this.

**Comment by kjpou1** [comment]
These are now marked obsolete as they will no longer work with the Renderer Pipeline.  These should be replaced to use CCLabel.
