### ISSUE TITLE
CCDrawNode.DrawSolidArc uses counterclockwise radians, not matching other behavior in CocosSharp.

### ISSUE THREAD

**Issue by vchelaru** [mono/CocosSharp#251]
I brought up rotation issues before, but we decided to leave them as-is. I thought I'd mention it here in case we want to make changes on DrawSolidArc.

CCNodes use clockwise rotation (opposite of traditional math) with angles as the unit.

CCDrawNode.DrawSolidArc uses counterclockwise rotation with radians as the unit.

**Comment by kjpou1** [comment]
@vchelaru 

Absolutely correct.  This should be fixed via commit https://github.com/mono/CocosSharp/commit/fb267035afb4d0992316691b8dad9c3fcf3ed420
