### ISSUE TITLE
CCDrawNode.DrawTriangleList ignores alpha values on the argument verts

### ISSUE THREAD

**Issue by vchelaru** [mono/CocosSharp#252]
The following code was used to reproduce the problem:
```
byte alpha = 100; // 255 is full opacity

CCV3F_C4B[] verts = new CCV3F_C4B[] {
	new CCV3F_C4B( new CCPoint(180,0), new CCColor4B(0, 255, 0, alpha)),
	new CCV3F_C4B( new CCPoint(210,60), new CCColor4B(0, 255, 0, alpha)),
	new CCV3F_C4B( new CCPoint(240,0), new CCColor4B(0, 255, 0, alpha))
};

base.DrawTriangleList (verts);
```

Results in the following:

[](https://dl.dropboxusercontent.com/u/21777714/GreenTriangle.PNG)

**Comment by vchelaru** [comment]
Not sure why github is having problems with images right, now, but here's a backup link:

https://dl.dropboxusercontent.com/u/21777714/GreenTriangle.PNG

**Comment by vchelaru** [comment]
Alpha values are also ignored on DrawLineList - lines are always full opacity.

**Comment by kjpou1** [comment]
@vchelaru 

The problem seems to be that BlendFunc is not being set correctly.  I added a new test showing this in the commit attached to this issue.

**Comment by kjpou1** [comment]
I am closing this.  See the test showing the use of BlendFunc as there was no need to change anything in our code base.  Please re-open if this does not fix the problem.

**Comment by vchelaru** [comment]
How come the BlendFunc needs to be set, instead of it defaulting to the appropriate blendfunc for that object so it "just works"?

**Comment by vchelaru** [comment]
Spoke to @kjpou1 about this, I now understand that we allow either premult or regular alpha blending, and if we assume one or the other, we'll break existing games.
