### ISSUE TITLE
ScreenOrientation.Landscape not working fully for Android

### ISSUE THREAD

**Issue by Heikofant** [mono/CocosSharp#258]
I want to run my game in ScreenOrientation = ScreenOrientation.Landscape, 
but unfortunately CocosSharp handles my App as
ScreenOrientation = ScreenOrientation.SensorLandscape so the content of the screen is flipped when I flip my device which I do not want.

Please fix this.

**Comment by kjpou1** [comment]
Please present an example for this.

In your Activity there is a setting for this.

    [Activity(
    Label = "Tests",
    AlwaysRetainTaskState = true,
    Icon = "@drawable/Icon",
    Theme = "@style/Theme.NoTitleBar",
    ScreenOrientation = Android.Content.PM.ScreenOrientation.Landscape,
    LaunchMode = Android.Content.PM.LaunchMode.SingleInstance,
    MainLauncher = true,
    ConfigurationChanges = ConfigChanges.Orientation | ConfigChanges.ScreenSize | ConfigChanges.Keyboard | ConfigChanges.KeyboardHidden)
    ]

**Comment by Heikofant** [comment]
using Android.Content;

....

[Activity (
		Label = "Prosodia",
		AlwaysRetainTaskState = false,
		Icon = "@drawable/icon",
		Theme = "@style/Theme.Splash", 
		LaunchMode = LaunchMode.SingleInstance,
		ScreenOrientation = ScreenOrientation.Landscape,
		MainLauncher = true,
		ConfigurationChanges = ConfigChanges.Keyboard |ConfigChanges.Orientation| ConfigChanges.ScreenSize|
		ConfigChanges.KeyboardHidden)
	]

As I said, the game will be flipped upside down if I flip my device upside down (so as I would be using ScreenOrientation.SensorLandscape).

Using the same Activity-Configuration for a regular Activity, it works as expected.

**Comment by kjpou1** [comment]
We use the Resouces Configuration as follows:

            View androidView = this.AndroidContentView;
            Orientation androidSuppOrientation = androidView.Resources.Configuration.Orientation;

            if((androidSuppOrientation & Orientation.Portrait) != Orientation.Undefined)
                supportedOrientations |= CCDisplayOrientation.Portrait | CCDisplayOrientation.PortraitDown;
            if((androidSuppOrientation & Orientation.Landscape) != Orientation.Undefined)
                supportedOrientations |= CCDisplayOrientation.LandscapeLeft | CCDisplayOrientation.LandscapeRight;

As from the documentation http://developer.android.com/reference/android/content/res/Configuration.html#orientation

The only thing that is returned back from here is Orientation.Portrait or Orientation.Landscape.

So what is it you are actually wanting this to do?

**Comment by Heikofant** [comment]
I assume you do not differentiate between Landscape, ReverseLandscape and SensorLandscape:   

     if((androidSuppOrientation & Orientation.Landscape) != Orientation.Undefined)
            supportedOrientations |= CCDisplayOrientation.LandscapeLeft | CCDisplayOrientation.LandscapeRight;

Well I need it to stick to Landscape and not to switch between Landscape and ReverseLandScape (LandscapeLeft and LandscapeRight in CocosSharp).

**Comment by kjpou1** [comment]
You can override the defaults that are set by using the following piece of code.

       public override void ApplicationDidFinishLaunching(CCApplication application, CCWindow mainWindow)
        {

            IGraphicsDeviceService service = (IGraphicsDeviceService)application.Game.Services.GetService(typeof(IGraphicsDeviceService));
            var xnaDeviceManager = (GraphicsDeviceManager)service;
            xnaDeviceManager.SupportedOrientations = DisplayOrientation.LandscapeLeft;
            xnaDeviceManager.ApplyChanges();

**Comment by Heikofant** [comment]
Thanks for your solution, it works.

But nevertheless I hope you will fix the supportedOrientations so they are exactly what I defined for my Android Activity :)

**Comment by kjpou1** [comment]
Heikofant

As per the documentation http://developer.android.com/reference/android/content/res/Configuration.html#orientation

The only thing that is returned back from here is Orientation.Portrait or Orientation.Landscape.

There is nothing we can really do about that.

**Comment by kjpou1** [comment]
Closing as resolved by workaround given above.
