### ISSUE TITLE
CCLabel: Quads updated even when not dirty

### ISSUE THREAD

**Issue by rtabbara** [mono/CocosSharp#259]
Within <code>CCLabel:VisitRenderer</code>, each glyph's corresponding quad command is updated with the new locally transformed quad via <code>CCSprite:UpdateLocalTransformedSpriteTextureQuads</code> irrespective of whether or not the quad is dirty. Avoiding this computation where possible should speed-up the rendering of labels.

**Comment by kjpou1** [comment]
Rami, I would agree with that opened issue except that CCLabel using system fonts never executes that code.

A system label uses a CCSprite and the only time there are any children is if one is specifically asked for using the this[] indexer and only for CCLabel's that are of CCLabelFormat.SpriteFont and CCLabelFormat.BitmapFont even support that.

The problem with the System Font label is that each time the text is changed a new native image is created and then that is then turned into a CCTexture2D and thus into a CCSprite.

So in effect if the this[] indexer is not used and the CCLabel is of type CCLabelFormat.SpriteFont or CCLabelFormat.BitmapFont then only piece of code that is actually executed in there is:

            quadCommand.GlobalDepth = worldTransform.Tz;
            quadCommand.WorldTransform = worldTransform;
                
            Renderer.AddCommand(quadCommand);

**Comment by rtabbara** [comment]
@kjpou1 Sure, I agree. However, in the event that users do index a glyph, it's unnecessary to be updating the corresponding quads every draw call.

**Comment by kjpou1** [comment]
@rtabbara 

Isn't that what this does?

        public void UpdateLocalTransformedSpriteTextureQuads()
        {
            if(texQuadDirty)
                UpdateSpriteTextureQuads();

            quadCommand.RequestUpdateQuads(UpdateLocalTransformedSpriteTextureQuadsCallback);
        }

**Comment by rtabbara** [comment]
No, because <code> UpdateLocalTransformedSpriteTextureQuadsCallback</code> is called regardless

**Comment by rtabbara** [comment]
No, because <code> UpdateLocalTransformedSpriteTextureQuadsCallback</code> is called regardless

**Comment by kjpou1** [comment]
Ok so basically we will need to make the texQuadDirty internal and check that correct?

**Comment by kjpou1** [comment]
By making texQuadDirty internal and then checking for this value in CCLabel before calling UpdateLocalTransformedSpriteTextureQuads() all actions are broken.

Closing for now as working.
