### ISSUE TITLE
[WP8.1] CCLabel System Font not working on Device

### ISSUE THREAD

**Issue by kjpou1** [mono/CocosSharp#260]
CCLabel-Windows: Unable to create the backing image of our text.  Message:    at SharpDX.Result.CheckError()
   at SharpDX.Direct2D1.Factory.CreateWicBitmapRenderTarget(Bitmap target, RenderTargetProperties& renderTargetProperties, RenderTarget renderTarget)
   at SharpDX.Direct2D1.WicRenderTarget..ctor(Factory factory, Bitmap wicBitmap, RenderTargetProperties renderTargetProperties)
   at CocosSharp.CCLabel.CreateTextSprite(String text, CCFontDefinition textDefinition)

**Comment by jonasbark** [comment]
additional debug information:

HRESULT: [0x8899000B], Module: [SharpDX.Direct2D1], ApiCode: [D2DERR_NO_HARDWARE_DEVICE/NoHardwareDevice], Message: No hardware rendering device is available for this operation.

I can possibly provide more information. And, if needed, I'm able to test a fix it on our devices.

**Comment by alexsorokoletov** [comment]
Also, MSDN tells that method CreateWicBitmapRenderTarget  is not supported on WP8.1 devices https://msdn.microsoft.com/en-us/library/windows/desktop/dd371309(v=vs.85).aspx

**Comment by kjpou1** [comment]
Closed via commit https://github.com/mono/CocosSharp/commit/0a2554e0ad41264b1dbea8384a4a7985093cc32f

**Comment by alexsorokoletov** [comment]
You are a man! :+1:

**Comment by zahik** [comment]
Thanks Kenneth!
Does it works also for WP8.1 SL?

**Comment by kjpou1** [comment]
I would think so.  The more tests the merrier though.  Give it a run-through and let us know for sure.
