### ISSUE TITLE
CCTouch errors when the parent of a CCNode is removed and added to the scene.

### ISSUE THREAD

**Issue by Heikofant** [mono/CocosSharp#271]
I have issues with touch events sent to a CCNode.
The node resides in a CCLayer and the CCLayer is added to a CCScene.
When I remove the CCLayer from the CCScene and add it again, the touch events for the CCNode are causing errors.

My CCNode receives touches through a  CCEventListenerTouchAllAtOnce with the method:

    public void HandleTouchesBegan (System.Collections.Generic.List<CCTouch> touches, CCEvent touchEvent)
		{			
			var location = touches [0].Location;		
			if (this.BoundingBoxTransformedToWorld.ContainsPoint (location)) {
				// doWork
			}
		}
    

the part
`var location = touches[0].Location` causes the following errors:

>[MonoDroid] Caused by: md52ce486a14f4bcd95899665e9d932190b.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
[MonoDroid] at CocosSharp.CCNode.ScreenToWorldspace (CocosSharp.CCPoint) <IL 0x00007, 0x0005c>
[MonoDroid] at CocosSharp.CCTouch.get_Location () <IL 0x0000c, 0x00067>
[MonoDroid] at TIL.PCL.Interface.MenuItems.AMenuItem.HandleTouchesBegan (System.Collections.Generic.List`1<CocosSharp.CCTouch>,CocosSharp.CCEvent) [0x00045] in /Users/heikoholz/Documents/Projects/TIL/TIL.PCL/Interface/MenuItems/AMenuItem.cs:123
[MonoDroid] at CocosSharp.CCEventDispatcher/<>c__DisplayClass6.<DispatchTouchEvent>b__4 (CocosSharp.CCEventListener) <IL 0x0009e, 0x002e9>
[MonoDroid] at CocosSharp.CCEventDispatcher.DispatchEventToListeners (CocosSharp.CCEventDispatcher/CCEventListenerVector,System.Func`2<CocosSharp.CCEventListener, bool>) <IL 0x00096, 0x0034f>
[MonoDroid] at CocosSharp.CCEventDispatcher.DispatchTouchEvent (CocosSharp.CCEventTouch) <IL 0x00164, 0x0076b>
[MonoDroid] at CocosSharp.CCEventDispatcher.DispatchEvent (CocosSharp.CCEvent) <IL 0x00049, 0x00153>
[MonoDroid] at CocosSharp.CCApplication.ProcessTouch (CocosSharp.CCWindow) <IL 0x00248, 0x00b17>
[MonoDroid] at CocosSharp.CCApplication.Update (Microsoft.Xna.Framework.GameTime) <IL 0x000b6, 0x00413>
[MonoDroid] at Microsoft.Xna.Framework.Game.<.cctor>b__19 (Microsoft.Xna.Framework.IUpdateable,Microsoft.Xna.Framework.GameTime) <IL 0x00002, 0x00030>
[MonoDroid] at Microsoft.Xna.Framework.Game/SortingFilteringCollection`1<Microsoft.Xna.Framework.IUpdateable>.ForEachFilteredItem<Microsoft.Xna.Framework.GameTime> (System.Action`2<Microsoft.Xna.Framework.IUpdateable, Microsoft.Xna.Framework.GameTime>,Microsoft.Xna.Framework.GameTime) <0x0029b>
[MonoDroid] at Microsoft.Xna.Framework.Game.Update (Microsoft.Xna.Framework.GameTime) <IL 0x0000c, 0x0004f>
[MonoDroid] at CocosSharp.CCGame.Update (Microsoft.Xna.Framework.GameTime) <IL 0x00002, 0x0002b>
[MonoDroid] at Microsoft.Xna.Framework.Game.DoUpdate (Microsoft.Xna.Framework.GameTime) <IL 0x0001b, 0x00087>
[MonoDroid] at Microsoft.Xna.Framework.Game.Tick () <IL 0x000f5, 0x00677>
[MonoDroid] at Microsoft.Xna.Framework.AndroidGameWindow.OnUpdateFrame (object,OpenTK.FrameEventArgs) <IL 0x00059, 0x0013b>
[MonoDroid] at OpenTK.GameViewBase.OnUpdateFrame (OpenTK.FrameEventArgs) [0x00014] in /Users/builder/data/lanes/1879/5f55a9ef/source/opentk/Source/OpenTK/Platform/Android/GameViewBase.cs:313
[MonoDroid] at OpenTK.Platform.Android.AndroidGameView.UpdateFrameInternal (OpenTK.FrameEventArgs) [0x00013] in /Users/builder/data/lanes/1879/5f55a9ef/source/opentk/Source/OpenTK/Platform/Android/AndroidGameView.cs:349
[MonoDroid] at OpenTK.Platform.Android.AndroidGameView.RunIteration (System.Threading.CancellationToken) [0x00096] in /Users/builder/data/lanes/1879/5f55a9ef/source/opentk/Source/OpenTK/Platform/Android/AndroidGameView.cs:569
[MonoDroid] at OpenTK.Platform.Android.AndroidGameView/<StartThread>c__AnonStorey0.<>m__0 (object) [0x0000d] in /Users/builder/data/lanes/1879/5f55a9ef/source/opentk/Source/OpenTK/Platform/Android/AndroidGameView.cs:459
[MonoDroid] at Android.App.SyncContext/<Send>c__AnonStorey1.<>m__0 () [0x00000] in /Users/builder/data/lanes/1879/5f55a9ef/source/monodroid/src/Mono.Android/src/Android.App/SyncContext.cs:32
[MonoDroid] at Java.Lang.Thread/RunnableImplementor.Run () [0x0000b] in /Users/builder/data/lanes/1879/5f55a9ef/source/monodroid/src/Mono.Android/src/Java.Lang/Thread.cs:36
[MonoDroid] at Java.Lang.IRunnableInvoker.n_Run (intptr,intptr) [0x00009] in /Users/builder/data/lanes/1879/5f55a9ef/source/monodroid/src/Mono.Android/platforms/android-21/src/generated/Java.Lang.IRunnable.cs:71
[MonoDroid] at (wrapper dynamic-method) object.f5cb27c4-ef3e-4001-b4d9-bca5c4ccca3b (intptr,intptr) <IL 0x00011, 0x0001f>
[MonoDroid] 	at mono.java.lang.RunnableImplementor.n_run(Native Method)
[MonoDroid] 	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:29)
[MonoDroid] 	at android.os.Handler.handleCallback(Handler.java:739)
[MonoDroid] 	at android.os.Handler.dispatchMessage(Handler.java:95)
[MonoDroid] 	at android.os.Looper.loop(Looper.java:135)
[MonoDroid] 	at android.app.ActivityThread.main(ActivityThread.java:5254)
[MonoDroid] 	... 4 more

The error only occurs when I remove and add the layer. When I remove and add the node itself, it's working properly.

**Comment by kjpou1** [comment]
Heikofant

Can you please provide an example for this.  Just a small solution that demonstrates the behavior.

**Comment by Heikofant** [comment]
ftp://mmolcmau@ftp.mmorats.com/www.mmorats.com/Heiko/TIL/TouchBug.zip

Just look at the method
`DoCrash()`
inside the `MainScene.cs`

**Comment by kjpou1** [comment]
Heikofant

First, thank you for the wonderful example code to reproduce the error.

When you remove the child layer you are actually also telling the remove to Cleanup and Dispose() the YellowLayer and children as well.  There are two parameters (CCNode node, bool cleanUp = true).  If you change this second parameter to false it should work as you expect.

The other thing is in the TestNode you probably should override OnExit and remove your touch listener as well.

We probably should check when the call to AddChild() is made that the node is not cleaned up or disposed.  Doing this would add extra processing for every AddChild which needs to be fast.  

There are a couple of things to consider here though.  

1. We could use an Assert but that only works with non Release development packages which we do no deliver so you will not get that Assert anyway.
2. We could do this check everytime and no add the child if it has been cleaned and disposed.  This would then cause questions of why it is not working.
3. We could do this check every time and throw an exception.

None of those are really performant because we are doing extra processing on each child add.

**Comment by Heikofant** [comment]
Thank you, that is exactly what I needed (`cleanUp=false)`.
