### ISSUE TITLE
[iOS] - Not able to play repeated sound effects

### ISSUE THREAD

**Issue by kjpou1** [mono/CocosSharp#273]
See forum post https://forums.xamarin.com/discussion/comment/141708#Comment_141708

Issue 2
I am trying to play an effect every time the user touches the screen with a simple call like:
CCSimpleAudioEngine.SharedEngine.PlayEffect ("sounds/Effects/Bumper1");
The effect is about 2 seconds long, and if I tap quickly in succession on Android I will hear multiple repeated immediate effects played fine on every touch.
On iOS the effect has to play to completion before a new version of the effect is heard. Is this a known limitation of the implementation on iOS or am I required to interrupt or setup explicit multiple channel support if I wanted to hear multiple effects at the same time?

**Comment by jamikado** [comment]
Here is a minimal sample project built from the default solution template for Android/iOS Shared PCL CocosSharp.
All it does is add a touch listener to the default blank CCLayer. Tap as fast as possible on Android and you will hear the bumper sound effect every tap. On iOS the current effect has to finish before another will play.
https://dl.dropboxusercontent.com/u/83837/SoundTest.zip

**Comment by kjpou1** [comment]
Closed via commit https://github.com/mono/CocosSharp/commit/65c001d8cb33dc1186a8bc30d64b6cd23a673981
