### ISSUE TITLE
CCNode.Visit() using CCRenderTexture results in all black texture

### ISSUE THREAD

**Issue by jonasbark** [mono/CocosSharp#275]
I used to create a "screenshot" from the current view using this:
```
CCRenderTexture renTxture = new CCRenderTexture(new CCSize((int)winSize.Width, (int)winSize.Height), new CCSize(winSize.Width, winSize.Height));
renTxture.BeginWithClear(new CCColor4F(CCColor3B.White));
rootNode.Visit();
renTxture.End();
```

While this has worked fine before 1.5 it now results in a black texture.
Can anybody confirm this? I'm using Windows Phone 8.1 and the specifically the commit 7e07f1674f from 19.07.2015 as I needed the fixed CCLabel.

**Comment by kjpou1** [comment]
@jonasbark The above code shows an example of screen capture.  See the following code:  https://github.com/mono/CocosSharp/blob/master/tests/tests/classes/tests/RendererTest/RendererTestDemo.cs#L334

**Comment by kjpou1** [comment]
This seems to be working on all platforms with the example code provided.  I am going to close this for now.
