### ISSUE TITLE
WP8.1: Bad performance when using CCLabel SystemFont

### ISSUE THREAD

**Issue by jonasbark** [mono/CocosSharp#278]
I thought I posted this on Tuesday, guess I forgot to submit the issue:

As an example I used the Windows 8.1 CocosSharp template and modified it slightly:

```csharp
 private CCPoint positionBegin;

        public IntroLayer() : base(CCColor4B.Blue)
        {

            // create and initialize a Label
            
            for (int i = 0; i < 20; i++)
            {
                CCLabel label = new CCLabel("Line " + 1, "Arial", 22, CCLabelFormat.SystemFont);
                //CCLabel label = new CCLabel("Line " + 1, "fonts/MarkerFelt", 22, CCLabelFormat.SpriteFont);
                label.Position = new CCPoint(i * 30, i * 30);
                AddChild(label);
            }

            // Register for touch events
            var touchListener = new CCEventListenerTouchAllAtOnce();
            touchListener.OnTouchesBegan = OnTouchesBegin;
            touchListener.OnTouchesMoved = OnTouchesMoved;
            AddEventListener(touchListener, this);
        }
        
        private void OnTouchesBegin(List<CCTouch> touches, CCEvent touchEvent)
        {
            this.positionBegin = touches[0].LocationOnScreen;
        }

        private void OnTouchesMoved(List<CCTouch> touches, CCEvent touchEvent)
        {
            float newPosX = Position.X + (touches[0].LocationOnScreen.X - positionBegin.X)/3.0f;

            Position = new CCPoint(newPosX, Position.Y);
        }
```

All it does is to move the IntroLayer slightly on touch so the performance worsening is visible. For some reasons the Labels aren't visible at all (even though they worked in another project just fine).

If you use the SpriteFont instead performance seems to be good enough.

**Comment by kjpou1** [comment]
@jonasbark 

The SystemFont is going to be very performance restrictive.  It does not take into account automatic batching as outlined [on the forum post here](http://forums.xamarin.com/discussion/46525/how-to-properly-cache-sprites-labels-textures-and-reduce-draw-calls) like the SpriteFont label does.  This is especially necessary on WP8.1 which does not seem to be very performant.  We have not been able to remedy this.

This is what the BitmapFont and SpriteFont labels really are meant for.  We may be able to do something in future with SystemFonts but as it stands now that is not the case.

Also, try this in your OnTouchesMoved:

        private void OnTouchesMoved(List<CCTouch> touches, CCEvent touchEvent)
        {
            //float newPosX = Position.X + (touches[0].Location.X - positionBegin.X) / 3.0f;
            float newPosX = Position.X + touches[0].Delta.X / 3.0f;

            PositionX = newPosX;// = new CCPoint(newPosX, Position.Y);
        }

That seems to do more of what you want it to do I think.

**Comment by kjpou1** [comment]
Closing this because it is known.  To take advantage of the Renderer Pipeline and automatic batching of resources then use SpriteFonts and/or BitmapFont which is what they were designed for.  This may be addressed in the future.
