### ISSUE TITLE
WP8.1: CCRenderTexture.SaveToStream results in black image

### ISSUE THREAD

**Issue by jonasbark** [mono/CocosSharp#279]
Following #275 (sorry for confusing) I noticed that the SaveToStream method doesn't seem to work.

```csharp
CCRenderTexture renTxture = new CCRenderTexture(Window.WindowSizeInPixels, Window.WindowSizeInPixels, CCSurfaceFormat.Color, CCDepthFormat.None, CCRenderTargetUsage.PreserveContents);
renTxture.BeginWithClear(new CCColor4F(CCColor3B.White));
Visit();
renTxture.End();

MemoryStream ms = new MemoryStream();
renTxture.SaveToStream(ms, CCImageFormat.Jpg);
```

I created a gist with the full source code for IntroLayer.cs based on the official CocosSharp Windows Phone 8.1 template: https://gist.github.com/jonasbark/fe221cd5eae085824734
It's a showcase that - upon ending the touch - creates a StorageFile from the current CCLayer Texture and shares that file so you can easily see it.

I'm not sure if it's an issue of CocosSharp or MonoGame. If it's MonoGame, would somebody be so kind to open up an issue on their GIT? I'm unable to provide informations without using CocosSharp.

**Comment by kjpou1** [comment]
Yes, you are not giving the new Renderer back end a chance to draw yet.  This is one of the changes that has happened with the v1.5 release.  

You will need to give it a chance to render first as [outlined in this forum post](http://forums.xamarin.com/discussion/45467/behavior-of-ccrendertexture-after-update).

You can get the info in the next render visit by doing the following after:

    CCRenderTexture renTxture = new CCRenderTexture(Window.WindowSizeInPixels, Window.WindowSizeInPixels, CCSurfaceFormat.Color, CCDepthFormat.None, CCRenderTargetUsage.PreserveContents);
    renTxture.BeginWithClear(new CCColor4F(CCColor3B.White));
    Visit();
    renTxture.End();

    // use a custom render command
        var saveToStream = new CCCustomCommand(() =>
            {
                MemoryStream ms = new MemoryStream();
renTxture.SaveToStream(ms, CCImageFormat.Jpg);
            }
        );
        Renderer.AddCommand(saveToStream);

       // ----  OR -----

       // use a schedule one 
        ScheduleOnce(
            (dt) =>
            {
                MemoryStream ms = new MemoryStream();
                renTxture.SaveToStream(ms, CCImageFormat.Jpg);
            }
            ,0

        );

Do one of the two but not both.  

Try that and let us know.

**Comment by jonasbark** [comment]
This works fine, indeed. Thanks a lot for pointing it out - I'll keep a closer look on the forum in the future!
