### ISSUE TITLE
Style: OnTouches* API

### ISSUE THREAD

**Issue by Therzok** [mono/CocosSharp#281]
Currently, the API in OnTouchesMoved and company are using a `List<CCTouch>` as a parameter. See [here](https://github.com/mono/CocosSharp/blob/38a4d98b4fb452cf536d0aaec60f6c25285d1c22/src/events/CCEventListenerTouchAllAtOnce.cs#L11-L18).

I personally prefer callback based things to not be modifiable. The API could probably return an `IReadOnlyList<CCTouch>` (preserving indexing, but not misleading towards a - you can modify this list), or an `IEnumerable<CCTouch>`?

**Comment by kjpou1** [comment]
Therzok

This makes sense.  We will look into it.  Not sure about the IReadOnlyList<CCTouch> though as that was only introduced in 4.5 if I remember correctly.  I think the IEnumerable<CCTouch> would be the safest.

**Comment by Therzok** [comment]
Going down the `IEnumerable<CCTouch>` is an API breaking change. Unless we can use IReadOnlyList, I see no use to switching to IEnumerable. Most of the samples use `touches[0]` too.

**Comment by kjpou1** [comment]
@Therzok I have already looked at this and there would be internal changes that would need to be done in our EventDispatcher which would include some casting to a List and back.  That would not be good.  It is more involved than just changing to IReadOnlyList<CCTouch> and needs some more analysis.  Sorry for not get back sooner.
