### ISSUE TITLE
Xamarin Studio templates don't work

### ISSUE THREAD

**Issue by eatdrinksleepcode** [mono/CocosSharp#289]
Operating System: OS X
Xamarin Studio Version: 5.9.5
MonoGame Addin Version: 3.4.0.455
CocosSharp Project Templates Version: 1.5.0.1

I am trying to start a CocosSharp project for the first time. I installed the CocosSharp extension in Xamarin Studio, and then attempted to create a new empty CocosSharp solution using the solution template. However, all I get is a "common" project, no Android or iOS projects. When I look on the file system, the folders for Android and iOS are there, but there are no files in them.

If I try to add a new CocosSharp iPad project to an empty solution, when I enter a project name and then hit the Create button, nothing happens. If I hit Create again, I am warned that the project already exists. The Create button is apparently creating the directory on disk, but then failing silently.

Does anyone know what is going on, or how I can figure out what is going on? Was really excited about trying out a new idea with CocosSharp this weekend, but this initial experience has kind of let the air out of my balloon.

**Comment by kjpou1** [comment]
Have just tried this as well myself.

Removed the templates, shutdown XS, open XS, Added templates again, create a new blank project and it all seems to be working.  Can you give anymore information here as to what the error could be?

Operating System: OS X
Xamarin Studio Version: 5.9.5
CocosSharp Project Templates Version: 1.5.0.1

Are you trying this with a Starter license maybe?

**Comment by eatdrinksleepcode** [comment]
Yes I am using the Starter license. I'm not sure why CocosSharp would care though.

**Comment by kjpou1** [comment]
Hey @eatdrinksleepcode 

That would be the reason.  We are in the process of getting MonoGame and thus CocosSharp whitelisted to be used with Starter and Indie.

This will be very soon and is in testing right now with the support just around the corner.  

Until then, unfortunately, there is no way to work with CocosSharp.

**Comment by eatdrinksleepcode** [comment]
Well that's disappointing.

What does whitelisting mean? I thought these were just project templates; but you are implying that even if I add CocosSharp to a project myself, I can't use it because of my Xamarin Studio license? That doesn't make any sense to me; it's just a library, right? I thought the only restriction of the Starter license was the size of the compiled application.

On a related note, it would be really nice if I had gotten a message warning me that my license is not supported. I don't know if that needs to be done in Xamarin Studio or in CocosSharp.

(Not directed at you, but Xamarin seems to be following the old Microsoft model of making it really difficult to get started on their platform...)

**Comment by kjpou1** [comment]
@eatdrinksleepcode it is based on the size of the application.  MonoGame is a very large code base and it counts as part of the overall application size right now.  Whitelisting mean that MonoGame and thus CocosSharp will not longer be counted as part of that size.

**Comment by kjpou1** [comment]
Also, just like I said this is right around the corner.  The pieces are being tested now.  ETA is still not available at this time though.

**Comment by eatdrinksleepcode** [comment]
Thanks for the explanation. It still doesn't really explain why the project templates don't work, and don't give any kind of messaging. I would expect the project to be created, and then the build to fail (with an appropriate error message).

**Comment by Therzok** [comment]
@eatdrinksleepcode Awkward question, but do you have Xamarin.Android and Xamarin.iOS installed? It's possible that the Xamarin Studio template engine to not know what kind of project to create if the target platform modules are not loaded.

**Comment by eatdrinksleepcode** [comment]
@Therzok fair question. According to the Xamarin Studio Add-In Manager, I do in fact have both Xamarin.Android and Xamarin.iOS installed. I actually was having a problem where the manager claimed that I had Xamarin.Mac installed, but I was getting a message saying it wasn't. So I downloaded a new copy of Xamarin Studio Starter Edition and installed it along with all of the platform plugins. So theoretically I should have everything I need (although, if I didn't, I would still expect some kind of messaging to that effect).

**Comment by Therzok** [comment]
@eatdrinksleepcode Can you attach the Xamarin Studio Log files under Help -> Open Log Directory? Specifically the Ide.* logs are what I'm interested in.

**Comment by eatdrinksleepcode** [comment]
@Therzok Interestingly, "Open Log Directory" does nothing. Can you tell me where the logs typically are?

**Comment by eatdrinksleepcode** [comment]
@kjpou1 Where should I be watching for information about when MonoGame and CocosSharp are officially whitelisted?

**Comment by Therzok** [comment]
@eatdrinksleepcode ugh, that is weird.

The logs are usually at `~/Library/Logs/XamarinStudio-5.0`

**Comment by kjpou1** [comment]
@eatdrinksleepcode Xamarin will have an official announcement.
