### ISSUE TITLE
CCContentManager.SharedContentManager.GetAssetStreamAsBytes(fontName, out fontName); cause too much memory overhead

### ISSUE THREAD

**Issue by imkow** [mono/CocosSharp#295]
![label_problem](https://cloud.githubusercontent.com/assets/380157/9641752/e63375b6-51ea-11e5-9507-7f7b499736bd.png)

It causes my app too slow loading a scene with several CCLabel. Unacceptably slow.
The image shows the data  collected by Xamarin Profiler. That's memory allocation when using CCLabel with Chinese TTF font. I checked your code in CCLabel-Android.cs (running on Android), GetAssetStreamAsBytes in CreateTextSprite() does nothing but check whether the font file asset can load. Am I right? Please fix the memory overhead problem.

**Comment by imkow** [comment]
Looks like GetAssetStreamAsBytes which invokes GetAssetStream() does unnecessary Stream.CopyTo(), the operation costs too much resources.

**Comment by Therzok** [comment]
I'm taking a look at this. For now, I can see a problem where the memorystream is being reconstructed many times, so setting a new memorystream with the old stream's length should be a good start.

**Comment by Therzok** [comment]
Actually, we can directly read into a `byte[]` from the stream, I'm going to do that.

**Comment by Therzok** [comment]
Can you try this [branch](https://github.com/mono/CocosSharp/tree/fixMemoryOverhead) and see if it fixes your problem? I'll come up with numbers soon.

**Comment by kjpou1** [comment]
@imkow Can you send us the .mlpd resulting file of the profiler output for this profiling session that you did.

**Comment by imkow** [comment]
i tested, it'ok now.  @kjpou1 still need it?

**Comment by Therzok** [comment]
@imkow any kind of profiling data would help me fix more cpu/memory issues.

**Comment by imkow** [comment]
@Therzok @kjpou1 no other issue in the profile resulting file, thanks. I will report if found any other problem.
