### ISSUE TITLE
CC 1.7.0 on WinPhone8.1 on Actual Device (lumia 520) GraphicProfile HiDef error

### ISSUE THREAD

**Issue by zahik** [mono/CocosSharp#330]
when succeeded to run game on emulator, 
when deploying game to real device i get: 
" warning could not find a graphic device that supports the HiDef profile"
I understand there are 2 profiles for winphone : Reach and HiDef  (and Reach is for Mobile phones and  HiDef is for Desktop)
but i don't know how to setup CC to profile 'Reach'

**Comment by zahik** [comment]
Is this is the problem on CCGameView.cs:
>    "  void InitialiseGraphicsDevice()
        {
            var graphicsProfile = GraphicsProfile.HiDef;
....
<

**Comment by zahik** [comment]
YES IT WAS!
changed it to 'GraphicsProfile.Reach' and it's working on my lumia 520
FYI

**Comment by kjpou1** [comment]
Great @zahik .  Thanks for letting us know.  We will need to take a look at this.

**Comment by zahik** [comment]
Good @kjpou1 
please look also on the other problem with XF 2.0.0 with CC 1.7.0 as i noted.
Thanks

**Comment by rtabbara** [comment]
@zahik This should now be fixed after ae5ea51 and will be included in our next release. Thanks for bringing it to our attention.

**Comment by zahik** [comment]
Thanks @rtabbara 
please also look on the other issue with XF 2.0.0
I opened also a bug : https://bugzilla.xamarin.com/show_bug.cgi?id=36303
I can't use the new XF 2.0.0 with WinPhone8.1 XAML , only XF 1.5.1.
Don't know if the problem is relate to you, is it with CC or XF, but at least you can guide the guys there.
Thanks very much!
Zahi
