### ISSUE TITLE
CCTransitionFadeTR causes crash

### ISSUE THREAD

**Issue by kjpou1** [mono/CocosSharp#334]
Prompted by forum post [here](https://forums.xamarin.com/discussion/57273/cctransitionfadetr-causes-crash#latest)

**Comment by rtabbara** [comment]
After #340 and #341, a <code>CCTransitionScene</code> now explicitly Disposes of any used node grids and their corresponding RenderTextures at the end of the transition, which will help to reduce the memory burden.
