### ISSUE TITLE
Unable to load Tiled TMX file using ZLIB base64 encoded data nodes

### ISSUE THREAD

**Issue by Krumelur** [mono/CocosSharp#337]
I created map in Tiled and it cannot be loaded with CocosSharp.
The data nodes are base64 encoded and ZLIB compressed. 

The compressed string in my test map is 112 characters long, my map is 100x100. I'd expect that to expand to 100x100 = 10000 elements. However inflating with ZLIB results in 16384 bytes, which would be 128x128 (https://github.com/mono/CocosSharp/blob/9acce26322ced620099a5a8e7aa2e8546da5db9b/src/tileMap_parallax_nodes/CCTileMapInfo.cs#L738)

As a consequence, the loading fails in https://github.com/mono/CocosSharp/blob/9acce26322ced620099a5a8e7aa2e8546da5db9b/src/tileMap_parallax_nodes/CCTileMapInfo.cs#L749

The loop goes from 0 to 9999 but tries to access the index * 4, which is outside the boundaries if the decoded bytes (16384).

The map is linked here:
https://dl.dropboxusercontent.com/u/111612273/Tiled_not_loading_in_CocosSharp.zip

**Comment by Krumelur** [comment]
I kind of cross-posted this on the Tiled forum and got an interesting answer: our decompression is not working! http://forum.mapeditor.org/t/please-help-me-understand-base64-encoded-zlib-compressed-data/975

**Comment by rtabbara** [comment]
Thanks @Krumelur. Will take a look.

**Comment by Krumelur** [comment]
Gist with proposals to fix: https://gist.github.com/Krumelur/c224d33dc5df16702dc4
