### ISSUE TITLE
Android does not render transparency properly

### ISSUE THREAD

**Issue by vchelaru** [mono/CocosSharp#348]
I used the following image:

![controllerhighlight](https://cloud.githubusercontent.com/assets/729631/12365186/6dda16dc-bb90-11e5-970d-07efd5d9143c.png)

This resulted in the following (image taken on Fire TV):

![cocossharprenderingissue](https://cloud.githubusercontent.com/assets/729631/12365272/0dce7836-bb91-11e5-82df-462d3e3a4efb.png)

Notice that the white pixels around the edges, which are not present in the original PNG. There are also whiter pixels around the inside as well.

Code to create sprite is as follows:

			controllerHighlight = new CCSprite ("ui/controllerhighlight.png");
			controllerHighlight.IsAntialiased = false;
			mainLayer.AddChild (controllerHighlight);
			controllerHighlight.ZOrder = 1;

**Comment by rtabbara** [comment]
As highlighted [here](http://forums.xamarin.com/discussion/24711/android-vs-ios-premultiplied-alpha-woes), one has to be careful when using native sprites with transparency on Android. In particular, setting the appropriate blend function should solve the issue

```
controllerHighlight.BlendFunc = CCBlendFunc.NonPremultiplied;
```
