### ISSUE TITLE
CocosSharp.Forms Game project does not appear in the templates for Xamarin Studio on Windows

### ISSUE THREAD

**Issue by vchelaru** [mono/CocosSharp#349]
I have installed CocosSharp through the addins and verified I'm working with CocosSharp 1.7.1. I do not see a CocosSharp.Forms game option on Windows Xamarin Studio, but I do in on Mac Xamarin Studio.

**Comment by kjpou1** [comment]
That is because XS for windows does not support iOS project yet.

**Comment by vchelaru** [comment]
Sure, but shouldn't I see a CocosSharp.Forms option that adds an Android project, the same way the non-forms project also appears on Windows and creates an Android project?

**Comment by rtabbara** [comment]
@vchelaru As XS on Windows neither supports iOS or WP projects, I'm not really sure of the value of having a Forms project that solely targets Android. More generally, I think any guides that are written would assume users are using XS on a Mac and VS on Windows. We can certainly revisit this if there appears to be a demand for XS on Windows, but for now I think it's best to close this off.
