### ISSUE TITLE
New project sets up GameView.Paused = true/false on iOS, but not on Android

### ISSUE THREAD

**Issue by vchelaru** [mono/CocosSharp#352]
The current project templates (1.7.1.0) set up code to pause and unpause the game when the containing ViewController is hidden/shown on iOS. There are no equivalent calls on Android.

It's not clear whether this is required on Android or not. If not, why does Android pause "automatically" but iOS does not. If so, shouldn't the template set this up so that both platforms behave consistently out-of-the-box?

**Comment by rtabbara** [comment]
@vchelaru On Android, this is handled internally within the `CCGameView` as the view itself can subscribe to be notified when the activity is in the foreground/background. On iOS, the setup is different as this logic is handled by the view controller. So in this instance the platform behaviours are not consistent. The motivation for the project templates is that a user should not have to worry about these discrepancies between the setup for the different platforms and focus on the common core game logic.
