### ISSUE TITLE
Google AdMob integration - iOS - Interstitial Ads - CC 1.7.1.0 Black Screen- new Problem

### ISSUE THREAD

**Issue by zahik** [mono/CocosSharp#355]
Hi Kenneth and Rami.
Found another bug on CC 1.7.1.0 for IOS.
post the problem here:
http://forums.xamarin.com/discussion/60043/google-admob-integration-ios-interstitial-ads-cc-1-7-1-0-new-problem
and here:
https://bugzilla.xamarin.com/show_bug.cgi?id=38178

I'm working on it over 3 days, it is VERY important because i cannot release my game with interstitial ads on it! 
No money!!!!!!
:)

Can you look at it please? 
please....

link to the IOS project file here:
http://cd8ba0b44a15c10065fd-24461f391e20b7336331d5789078af53.r23.cf1.rackcdn.com/xamarin.vanillaforums.com/FileUpload/bf/869a9bbedeaa4f7e96c57af9b1c593.zip

Thanks

Zahi Kramer

**Comment by rtabbara** [comment]
@zahik Thanks. I'm able to reproduce this problem and we'll take a look at the issue. As you've seen in this forum post [here](https://forums.xamarin.com/discussion/35692/interstitial-ad-in-admob-throws-nullreferenceexception), it appears to be tied to the `iPhoneOSGameView` so we have a good starting point.

**Comment by zahik** [comment]
@rtabbara Great! Thanks.
Looking forward to the fix.
Regarding the post [https://forums.xamarin.com/discussion/35692/interstitial-ad-in-admob-throws-nullreferenceexception](https://forums.xamarin.com/discussion/35692/interstitial-ad-in-admob-throws-nullreferenceexception)
As you see there i didn't have the exception mentioned there, but events won't fire on CC (on XF everything was good).
But.
I succeeded to find a workaround to that problem.
On CC for some reason the Delegate object of Admob InterstitialAd object turned to be null (inside XF after registering events it wasn't null , but when activating the game in CC and firing from there the Admob InterstitialAd object , his propery "Delegate" (of type InterstitialAdDelegate) was null.
So,
I Re registered the events inside CC (created new InterstitialAdDelegate object) and re registered the events , and now THE EVENTS START FIRING.
FYI

**Comment by rtabbara** [comment]
@zahik There's a proposed fix for this in 9346063. If possible, can you build from source and see if this sorts out the issues you are encountering?

**Comment by zahik** [comment]
@rtabbara 
Thanks Rami 
I'll check it.

**Comment by zahik** [comment]
WORKING!
Great!
Thanks Rami!
Saw your fix.
It should have worked also without it, isn't it?
:)
God of Software works in his mysterious ways....

**Comment by rtabbara** [comment]
@zahik Glad to hear that it works. This fix will feature in our next release.
