### ISSUE TITLE
Visual Studio template only creates a Android project, Xamarin Studio creates PCL+Android+iOS

### ISSUE THREAD

**Issue by vchelaru** [mono/CocosSharp#358]
Visual Studio templates should behave the same as Xamarin Studio templates, creating a PCL+iOS+Android project. Otherwise users who want to develop for iOS must do a bit of setup.

**Comment by vchelaru** [comment]
Furthermore, the default Android game for Visual Studio has a blue background with a "Hello CocosSharp" label. The VS template should be consistent with the XS template.

**Comment by YPakhomau** [comment]
Yes, i can confirm there is no option to create windows app right now.

**Comment by rtabbara** [comment]
@YPakhomau This issue is a duplicate of #388 , which has been added to our release schedule
