### ISSUE TITLE
Is CCApplication & CCApplicationDelegate obsoleted?

### ISSUE THREAD

**Issue by hermanhmchan** [mono/CocosSharp#369]
I studied the sample GoneBanana which uses a class derived from CCApplicationDelegate to define the behaviour of application for enter background / foreground etc.
But it references CocosSharp v1.3.2.0

In latest version 1.7.0.0, these two classes disappeared. When create project from template, it doesn't create a class derived from CCApplicationDelegate. May I know how to handle the events enter background / foreground in latest version? Thanks.

**Comment by rtabbara** [comment]
@hermanhmchan Yes, see [here](https://forums.xamarin.com/discussion/55345/cocossharp-v1-7-0-0-pre1-embeddable-game-view-and-xamarin-forms-support)
