### ISSUE TITLE
Unified CCLabels

### ISSUE THREAD

**Issue by rtabbara** [mono/CocosSharp#37]
There are currently a lot of (understandable) misunderstandings between all the different flavours of labels (CCLabel, CCLabelTtf, CCLabelBMFont, etc.). In addition, the fact that these classes are derived from different parents (CCSprite/ CCSpriteBatchNode) also gives rise to further maintenance issues.

Ideally, we should just have a single CCLabel class with a basic constructor

<pre>
<code>
CCLabel("foo", "arial", 22, CCLabelType.Ttf)
</code>
</pre>

We should also have a default <code>CCLabelType.Auto</code> that first attempts to locate fonts within the Content folder and then as a last resort attempts the Ttf version of the font if no font files were found. 

CCLabel should be derived from CCNode as a container object, with specific-ivars for the different label flavours.

**Comment by kjpou1** [comment]
Will be available in upcoming V1.4.0.0 release of CocosSharp which is being prepared.
