### ISSUE TITLE
iOS: If only landscape orientation is enabled, app with a wrong window position

### ISSUE THREAD

**Issue by vancura** [mono/CocosSharp#40]
If only landscape orientation is enabled, app with a wrong window position. This is how it looks when launched:

![screen shot 2014-10-16 at 12 31 35](https://cloud.githubusercontent.com/assets/4982/4661114/a23c2c22-551f-11e4-9122-661a188b18b0.png)

As soon as the screen is rotated to the other landscape mode, everything is fine:

![screen shot 2014-10-16 at 12 32 13](https://cloud.githubusercontent.com/assets/4982/4661123/b4f35142-551f-11e4-8d8d-b10ec802f12a.png)

And since then it's always fine.

It could be connected with #39.

**Comment by mitko9000** [comment]
First sorry to write inside a closed issue but I have the same problem using monogame from NuGet
Here is the issue : http://community.monogame.net/t/ios-strange-screen-problem/2072/5

Can you tell me how this was resolved ?
