### ISSUE TITLE
iOS: BackgroundMusicVolume has no effect

### ISSUE THREAD

**Issue by mikebluestein** [mono/CocosSharp#44]
I tried setting the volume in the GoneBananas sample like this:

CCSimpleAudioEngine.SharedEngine.BackgroundMusicVolume = 0.02f;

but it had not effect.

**Comment by Tonisson** [comment]
I'm using version 1.3.1.0 and BackgroundMusicVolume still does not seem to have any effect.

I have these lines:
            CCSimpleAudioEngine.SharedEngine.PlayBackgroundMusic("Sounds/GameMusic", true);
            CCSimpleAudioEngine.SharedEngine.BackgroundMusicVolume = 0.8f;
When I step over them in the debugger, BackgroundMusicVolume is still set at 0.

Any ideas on what I might be doing wrong?

**Comment by rtabbara** [comment]
Glad to hear it works! I was trying to look for your earlier comment on github, but couldn't find it :)
