### ISSUE TITLE
CCTXTileMap: Scrolling issue

### ISSUE THREAD

**Issue by rtabbara** [mono/CocosSharp#54]
From the forums:

http://forums.xamarin.com/discussion/27152/simple-tilemap-tmx-scroller

I am loading a timemap with this CCTMXMapInfo mapInfo = new CCTMXMapInfo ("lvl01.tmx"); map = new CCTMXTiledMap (mapInfo);

I tried using a camera but got perspective camera when moving it... (maybe a missed parameter?)

Then I ended up just setting the design resolution size like this to fit the height of the tile map mainWindow.SetDesignResolutionSize (568, 320, CCSceneResolutionPolicy.FixedHeight);

but am now missing the part where I can move the map.

I added a simple sprite to move across the screen but for some reason couldn't get the ccfollow action to work quite right. Maybe I need to add the map to a special node and then use the action on that?

Any help and pointers are appreciated :-)

**Comment by kjpou1** [comment]
Finishing fixes for this issue https://github.com/mono/CocosSharp/commit/01adb7a278b118de2d15a10dbe53599e8365e9ea
