### ISSUE TITLE
CocosSharp and Forms

### ISSUE THREAD

**Issue by kjpou1** [mono/CocosSharp#57]
https://github.com/Sohojoe/CocosSharp-Forms-sample

I was able to get forms to start a CocoSharp session, but I got stuck when trying to close down CosoSharp and resume forms - is this possible with the current state of play?

**Comment by dvdsgl** [comment]
This is a test comment that will be removed in a moment. A colleague is having issues with notifications on this repo and we're trying to debug it. Sorry for the noise!

**Comment by bgiromini** [comment]
+1. It would be nice to use Xamarin Forms to build a user management system and then use CocosSharp as the game UI.

**Comment by AGRocks** [comment]
Any updates on that? Will gladly help with any work needed to integrate Forms.

**Comment by rtabbara** [comment]
@AGRocks We're very close to a prerelease package which provides Forms support. Once that's out, any help with tracking bugs and/or other contributions would be fantastic.

**Comment by kjpou1** [comment]
Take a look here: https://forums.xamarin.com/discussion/55347/cocossharp-v1-7-0-0-pre1-release-notes
