### ISSUE TITLE
"CocosSharp for Windows Phone 8" Nuget package doesn't work with WP 8.1 app

### ISSUE THREAD

**Issue by crpietschmann** [mono/CocosSharp#6]
The current "CocosSharp for Windows Phone 8" v1.0.0.0 Nuget package can not be installed into a Windows Phone 8.1 project within Visual Studio 2013. Nuget says the following:

Could not install package 'CocosSharp.WindowsPhone8 1.0.0.0'. You are trying to install this package into a project that targets 'WindowsPhoneApp,Version=v8.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

![cocossharpwp81nugeterror](https://cloud.githubusercontent.com/assets/392297/4018368/66a76cd8-2a4c-11e4-8ff8-5703b20fb830.PNG)

**Comment by kjpou1** [comment]
This is closed with v1.4.0 of CocosSharp

See issue https://github.com/mono/CocosSharp/issues/172
