### ISSUE TITLE
Significant Stutter on Android

### ISSUE THREAD

**Issue by kjpou1** [mono/CocosSharp#64]
From forum post: https://forums.xamarin.com/discussion/27563/simple-android-game-has-significant-stutter

Moving Android to OpenTK-1.0

Commit by Dean to move Android to OpenTK-1.0
https://github.com/mono/MonoGame/commit/d154dcd0d0a18e7d879ba80b21bb6998bd4cc3b0

*Upgrade Android to OpenTK-1
Also added Property to Activity to control if the rendering is done on
the UI thread or not. By not rendering on the UI thread we save
a SyncContext.Send call in the underlying AndroidGameView.
This can introduce up to a 100ms delay in a Render call which
can cause a stutter.

By default we will leave RenderOnUIThread = true to maintain
backwards compatability.

The upgrade to OpenTK-1 was required as the fix for this
is not present in the OpenTK 0.9.9.3 version as it is there
for backwards compatabiltiy only.

**Comment by rtabbara** [comment]
The upcoming <code>CCGameView</code> when targeting on Android leverages OpenTK-1's ability to renders off of the UI thread, and hence no longer suffers from the previously reported stuttering.
