### ISSUE TITLE
Add error message (exception?) when textures and sprite fonts are missing

### ISSUE THREAD

**Issue by vchelaru** [mono/CocosSharp#72]
When creating a CCSprite users can make lots of mistakes.  If a CCSprite doesn't appear new users won't know why.  Is it off screen?  Is it transparent?  Was it not added to a Layer?  Is the texture format wrong?  Is the texture missing?

If we can communicate when it is a missing texture this will help solve a lot of problems.

This is especially important with SpriteFonts which have an even more obscure method of working.  You have to reference them by font family/size rather than the actual xnb, and the files have to be in a particular folder.  This has very low discoverability and exceptions would go a long way to help users out here.

**Comment by kjpou1** [comment]
See https://github.com/mono/CocosSharp/issues/96 to be released for v1.3.1.0
