### ISSUE TITLE
Allow more flexibility in referencing sprite font XNBs

### ISSUE THREAD

**Issue by vchelaru** [mono/CocosSharp#73]
SpriteFont xnbs can be referenced and used in code under the following conditions:
* File is under the Assets/content/fonts folder (Android) or content/fonts (iOS)
* File must be in the format [FontFamily]-[FontSize].xnb.  Even missing dashes will result in the font not being found
* "fonts" folder must be lower-case

All of these seem unnecessarily strict for users, or at least the strictness could be eased if users were allowed to reference fonts directly by name, the same way they can reference texture .xnb's by name.  Suggestions:

    label = new CCLabelTtf("DisplayText", "CustomXnbName");
or

     label = new CCLabelTtf("DisplayText", "Some/Other/Folder/FontXnbName");
or

     label = new CCLabelTtf("I will set my font on the next line...");
     label.SetFontFromXnb("Could/Use/Any/FontXnbName");

**Comment by kjpou1** [comment]
Closed via https://github.com/mono/CocosSharp/commit/604efb4618b38ddcb757c5bc8b351b4cd5ad4085
