### ISSUE TITLE
CCLabel: border artefacts when initially rendering characters

### ISSUE THREAD

**Issue by rtabbara** [mono/CocosSharp#76]
Observed in Nibbles project [here](https://github.com/jamesmontemagno/nibbles). On initial load, menu labels have borders around characters, however the label should be a solid white character.

When returning from another layer, the menu labels however are correctly rendered.

**Comment by jarnsater** [comment]
I have the same issue in my own project, and have also noticed those weird artifacts in the Nibbles project. It's even visible in the screenshots on the project page.

I don't see the same issue in the GoneBananas sample, but it's using CCLabelTtf (with packaged content).

Also, I've noticed that if I use BlendFunc = CCBlendFunc.AlphaBlend for a CCLabel, the result is much better (but not perfect, still a few artifacts appear).

**Comment by kjpou1** [comment]
The Unified Label rewrite of CCLabel has confirmed to fix this problem.  See issue https://github.com/mono/CocosSharp/issues/37
