### ISSUE TITLE
RemoveSpriteFrame

### ISSUE THREAD

**Issue by simonsheehy** [mono/CocosSharp#81]
Hi!

I just find an issus in the CCSpriteFrameCache.cs function RemoveSpriteFrame on line 386.

When I try to remove a frame who is not an Aliases, I receive this message : The given key was not present in the dictionary. And for the same reason, the function RemoveSpriteFrames(PlistsDictionary dictionary) can't work, the list keysToRemove is initiate empty and values are never added, just removed (line 417). 

Thanks

**Comment by kjpou1** [comment]
Closed by commit https://github.com/mono/CocosSharp/commit/c24ac0f927bdcac036ab562f8a9df444dbfee022
