### ISSUE TITLE
No support for different screen orientations

### ISSUE THREAD

**Issue by hig-ag** [mono/CocosSharp#84]
Hello,

in the current version of CocosSharp it is impossible to support landscape and portrait mode. Is this behaviour intended? This feature is really neccessary, especially if you develop board games.

Additional info:

The setter of CCDrawManager.SupportedDisplayOrientations is never called.
The supported display orientations are only set on the construction of CCDrawManager with the value of CCApplication.PlatformSupportedOrientations()
Related issue: https://github.com/mono/CocosSharp/issues/25

**Comment by rtabbara** [comment]
Hi,

<code>PlatformSupportedOrientations</code> will fetch the allowed orientations that have been set externally by the user. So for instance, on iOS, you would set your desired orientations within the Info.plist and these will then be set when initialising the <code>CCDrawManager</code>.

**Comment by rtabbara** [comment]
Closing for now as I'm unable to replicate this issue.
