### ISSUE TITLE
Enhance CCSprite() to handle Content not being found

### ISSUE THREAD

**Issue by bryonbaker** [mono/CocosSharp#95]
CCSprite() does not provide a notification if the sprite is not found. Having some form of feedback to assist with debugging would be useful.

**Comment by kjpou1** [comment]
See https://github.com/mono/CocosSharp/issues/96

This should allow users to see the message output from CocosSharp.  

It will print out something like ** Texture Images/grossini2 was not found **.

If you want to be sure then you can always check in your code for 

    if (sprite.ContentSize == CCSize.Zero)

If the ContentSize is CCSize.Zero then the Sprite was not loaded.
